# DEPLOYMENT PIPELINE - Maps to AWS CodeDeploy + CodeBuild combined
name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Test Pipeline"]
    types: [completed]
    branches: [main]

permissions:
  contents: write  
  pages: write
  id-token: write


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    # SOURCE STAGE
    - name: Checkout code
      uses: actions/checkout@v4
      
    # BUILD ENVIRONMENT SETUP
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    # BUILD STAGE
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Build application
      working-directory: ./frontend
      run: npm run build
      
    # DEPLOYMENT STAGE
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build